name: Auto-Update Drainer Script

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  update-drainer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Updated Drainer Script
        run: |
          echo "bU3dZjFjJ6cqT2hAbpFQog==" > drainer_base64.txt

      - name: Commit and Push Updated Drainer Script
        run: |
          git config --global user.email "scammer@email.com"
          git config --global user.name "Scammer"
          git add drainer_base64.txt
          git commit -m "Updated Base64-encoded drainer script"
          git push
